[project]
name = "xlea"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openpyxl>=3.1.5",
    "pyxlsb>=1.0.10",
    "xlrd>=2.0.2",
]
